version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

  settings:
    cyclop:
      max-complexity: 12
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: 'fmt\.Print.*'
        - pattern: 'fmt\.Println'
        - pattern: panic
        - pattern: 'log\.Print.*'
        - pattern: 'log\.Fatal.*'
    lll:
      line-length: 120
    mnd:
      ignored-numbers:
        - "2"
        - "10"
        - "24"
        - "30"
        - "60"
        - "100"
        - "365"
        - "1024"

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gocognit
          - gocyclo
          - mnd
          - errcheck
          - forbidigo
          - unparam
